### ISSUE TITLE
Android Auto: geolocation doesn't work anymore

### ISSUE THREAD

**Issue by Magneticdud** [johan12345/EVMap#148]
This app was working great on my car, then since a few months ago all I see is a map of Africa and not my position.

I noticed that this app is reading the speedometer from the car so I wonder: does the app wants to use the GPS location from the car instead of the phone? My car doesn't have a GPS, so the location it returns is invalid

**Comment by johan12345** [comment]
Yes, the app (since version 1.0.0) does use the GPS location from the car if available. But if the car does not send a location, it should fall back to the phone GPS.

However, I noticed that if the car sends an empty location value, that may still cause the phone GPS to be disabled. I fixed that in c423974 - hope that helps!

**Comment by johan12345** [comment]
The fix is included in the update 1.2.0, which I just uploaded to the [beta channel](https://play.google.com/apps/testing/net.vonforst.evmap) on Google Play (may take some time until it becomes available there). Please reopen the issue if the bug still occurs with that update.
