### ISSUE TITLE
Offline support for openchargemap.org

### ISSUE THREAD

**Issue by fhvyhjriur** [johan12345/EVMap#156]
Thanks to https://github.com/johan12345/EVMap/pull/96 there is openchargemap.org as datasource. Could you add the functionality to use this data with a map when offline?
Other then https://github.com/johan12345/EVMap/issues/88 there are no restrictions like for example 24-hours on the openchargemap.org data. Thats why i open this as a different issue. Different data source, different issue.

**Comment by johan12345** [comment]
Thanks!

I would like to try and keep the implementation for offline storage as reusable as possible (by storing the data in EVMap's own internal data structure, not in the formats used by the different APIs) so that offline use will be automatically supported for other data sources as well if added in the future. Each data source could then provide an info about the maximum storage duration (i.e. 24h for GoingElectric or infinity for OCM) so that the app can decide when to consider the data as invalid.

So, as the implementation would be mostly the same, or at least very closely linked, I don't really see much use in tracking offline support for the different data sources in separate issues. Closing this in favor of #88

**Comment by fhvyhjriur** [comment]
Thanks for keeping track of that functionality. If you need some testing, i could test on F-Droid. F-Droid have the capability of releasing testing versions the people could then manually install. The most famous example is F-Droid itself that have testing releases of F-Droid 1.14 but the automatic installation is still the stable 1.13 version.

**Comment by johan12345** [comment]
Thanks, also for your other comments and feature requests. I think at the moment the limiting factor is not the capacity to test, but my limited spare time to develop these features in the first place 😉. As you can see, the wishlist is already pretty long. This is an open source project after all, so contributions from others are very welcome. So far there have been [no major ones](https://github.com/johan12345/EVMap/pulls?q=is%3Apr+is%3Aclosed) 😞

**Comment by programmin1** [comment]
I was surprised it shows no stations in USA if there is no data/wifi. I mean it may as well be a web site.

If no one has started this I would like to look at this for Hacktoberfest.

**Comment by johan12345** [comment]
Please see issue #88 and PR #164 for the current progress - this one (#156) is a duplicate issue and has thus been closed.

So in principle the basis for offline caching is implemented, but there are still a couple of points left to make the UX convincing. Also, there is no way yet to manually download all chargers (which will be needed for #97 and is probably also a good idea for OpenChargeMap - but should not be enabled for GoingElectric.de as their terms of use prohibit it).

If you would like to help with some part of this, you're welcome to take a look, I probably won't have much time to continue on that PR this month.
