### ISSUE TITLE
save different sets of filters as profiles

### ISSUE THREAD

**Issue by johan12345** [johan12345/EVMap#16]

**Comment by TweetsOfNiklas** [comment]
Maybe also add pre-made filters aka cars. If someone selects an Ioniq it only shows CCS, Type2, CEE and the normal household plug. And for people who use multiple cars it would be great to add these cars to favorites.

**Comment by johan12345** [comment]
Not sure if we should pre-built profiles for different cars, because this also depends on which adapters you have (at least for the AC plugs). But if this is implemented you can definitely add different filter profiles for multiple cars.

**Comment by TweetsOfNiklas** [comment]
Yeah, true.

 
 

Gesendet: Freitag, 22. Mai 2020 um 20:32 Uhr
Von: "Johan von Forstner" <notifications@github.com>
An: "johan12345/EVMap" <EVMap@noreply.github.com>
Cc: "Niklas Ruby" <niklas.ruby@gmx.at>, "Comment" <comment@noreply.github.com>
Betreff: Re: [johan12345/EVMap] save different sets of filters as profiles (#16)


 

Not sure if we should pre-built profiles for different cars, because this also depends on which adapters you have (at least for the AC plugs). But if this is implemented you can definitely add different filter profiles for multiple cars.
