### ISSUE TITLE
Android Auto/Automotive: show/hide menu

### ISSUE THREAD

**Issue by greentux** [johan12345/EVMap#178]
Menu needs around 20% of the area in Android Automotive. Better to show/hide the Menu by tapping "EVmap" in the Top.

**Comment by johan12345** [comment]
Unfortunately, the Android Auto/Automotive templates do have an option to hide the menu.

Also, the map on the initial page does not show any POIs, it is basically just decoration until you tap either "near me" or "favorites". The templates require each POI on the map to be related to an item shown in the menu (probably also due to driver distraction reasons - tapping a small marker on the map while driving is much harder than a menu item on the left side of the screen). So when the menu just shows top-level navigation there is no way to show chargers on the map.

While I understand this would be useful and make the AA app behave more like the smartphone app, I doubt Google will make such substantial changes to the template concept. 🫤
