### ISSUE TITLE
Android Auto/Automotive: Show POIs already on startup page

### ISSUE THREAD

**Issue by greentux** [johan12345/EVMap#179]
Map should show (filtered) POI while driving.

**Comment by johan12345** [comment]
With POI, do you mean the current location of the car? I usually refer to the charging stations as POI (points of interest) 😉

**Comment by greentux** [comment]
No I mean the Charging stations. After starting the app I expect a live map with POI. But there is only a naked map. In #178 you say, that there is no information possible till pressing a menu. 
So I would prefer:
- replacing this "useless" startup map with a logo
- having a menu action with "live" meaning "live carposition with renewing the POI every x seconds...

possible?

**Comment by johan12345** [comment]
> replacing this "useless" startup map with a logo

I could use a grid of buttons for the startup page, instead of the map with menu.

On the other hand, Google does show examples of a similar page with a map and no POIs in their [design guidelines](https://developer.android.com/training/cars/Android%20for%20Cars%20App%20Library%20design%20guidelines.pdf) (on the right):
<img width="658" alt="image" src="https://user-images.githubusercontent.com/5310424/174867335-f1a9c65e-daf1-49f8-aaf4-d2a694208116.png">

> having a menu action with "live" meaning "live carposition with renewing the POI every x seconds...

No, refreshing automatically is also not possible so far, as Google limits the number of updates of the template (where each change that updates the titles of the list items counts as one update). I have also raised this as an issue in the [Google Issue Tracker](https://issuetracker.google.com/issues/176694222).
But I saw in your screenshots that there is a refresh button at the top right corner of the menu - does that work at least? Support for this has been added in a recent update of the Car App Library, but the UI did not show up so far in Android Auto.

**Comment by greentux** [comment]
mmmh, I can only say, that the expectation with a "map" on startup is a "map with POI"...
But perhaps some other people will send in feedback.
Filter is definitiv the most needed one :)

**Comment by greentux** [comment]
btw the refresh button works...

**Comment by johan12345** [comment]
I found another solution: I removed the 4 top-level navigation items (*Nearby, Favorites, Vehicle Data, Settings*) and instead go directly to the *Nearby* view by default. That fixes this issue and also removes one layer of navigation depth, which is needed to be able to implement creation/editing of filter profiles (because the templates limit the number of layers to 5).

Switching to *Favorites* will then be done through the filter button, just as on the phone. *Settings* can be accessed through another button next to the filter button, and *Vehicle Data* (which is not very useful in most cars) is moved to be a sub-item of *Settings*.

Now the only problem is that I can't add a third button in the top right to implement a place search function (#186)... I have to think about that.
