### ISSUE TITLE
No fallback to coarse location

### ISSUE THREAD

**Issue by cremor** [johan12345/EVMap#214]
I noticed that since recently the app doesn't find my location any more when I'm inside a building. I assume it requires GPS reception and doesn't fallback to the coarse location.

Steps to reproduce:
1. Be inside a building, close all apps, disable GPS.
2. Enable GPS, open EVMap.
3. Notice that EVMap doesn't find the current location.
4. Open Google Maps.
5. Notice that Google Maps immediately finds the current location.

Might be related to 720d52285dde867094cad045cc6f5de8882d33c0 since that was around the time I first noticed the problem.

EVMap 1.3.7-google
Android 9

**Comment by johan12345** [comment]
Yeah, the last update [removed](https://github.com/johan12345/EVMap/commit/b445be99bba5f81fa9cea2e397d39cd981f5e7d8) the [Lost](https://github.com/lostzen/lost) library because it has been unmaintained for many years, is slightly overkill for what we actually need, and was the only dependency that still relied on the [AndroidX jetifier](https://github.com/johan12345/EVMap/commit/c60043f925df9922d76e24daafca84658e15140f), which slowed down the build process.

Instead, I switched back to Android's own location API - however, that requires you to query each location provider (network, GPS) separately and apparently the function that decides which one is "best" doesn't take into account if GPS has no reception inside a building.

On Android 12 and above there is also a new fused location provider which internally combines the signals from network and GPS location providers. But for older Android versions this functionality is only available through Google Play Services (which at least the F-Droid version of EVMap cannot depend on), so we need to implement that ourselves (ans Lost did before). So in 41cb6cf I adapted the `FusionEngine` from Lost. I hope this will solve the problem!
