### ISSUE TITLE
Boolean filter for high price operators

### ISSUE THREAD

**Issue by Ixam97** [johan12345/EVMap#249]
Hello!
I already wrote in your GoingElectric-Thread about this and thought a bit more about it.

It would be nice to have an option to filter for high price operators to circuvent the API-limitations when applying network and payment filters at the same time. E.g. "Allow high price Operators" as a boolean filter.
This would be a little bit of manual labour, but currently I only know of Ionity as a high price operator in europe. Maybe it would be possible to implement it as a local filter just like filtering for the number of connerctors per location.

Not a big deal to "manually" ignore Ionity, but maybe a nice QOL addition.

**Comment by johan12345** [comment]
Hmm, I would not be in favor of a specific filter for Ionity in addition to the already existing option to filter by operator. 
Whether Ionity is "high price" or not depends entirely on what charging plan you use. E.g., Bonnet or Elli offer pretty good deals for Ionity, and ad hoc prices at some other operators, e.g. Fastned and Tesla Superchargers for non-Teslas, are already even more expensive than Ionity (>0,80€/kWh in Germany).

What you actually want is the possibility to combine the filters by operator and charging card with an "AND" condition instead of "OR". In principle it would be possible to implement this as a local filter, but the big downside to local filters is that they cannot be combined with using server-side clustering - so the performance drops quite significantly on low zoom levels, especially if not many other filters are applied.

As a workaround, you could change your filter to only use the operator filter - either by just selecting the ones that you know are compatible with your charging cards, or just selecting all operators except Ionity (because in the countries they support I think it's very rare to find an operator that is not supported by EnBW mobility+).

**Comment by Ixam97** [comment]
Thanks for the response. I get that point and you are right. But as far as I know Ionity is the only operator where other charging cards generally do not charge the standard prices but a higher one.
Tesla for example does not accept any other card providers, which differs it from Ionity, meaning such a switch would not be necessary when using a card provider filter. You could also call it just "Allow Ionity" as the mobility+ app does it.

But the decission is on you, just a suggestion 👍

**Comment by johan12345** [comment]
> But as far as I know Ionity is the only operator where other charging cards generally do not charge the standard prices but a higher one.

I wouldn't say this is generally true, in the meantime many MSPs have added more CPOs than Ionity to their list of "high-price" operators (e.g. many providers that are part of Ladenetz have included Aral and has.to.be, and [e.on](https://www.eon.de/de/pk/e-mobility/unterwegs.html) even more).

> You could also call it just "Allow Ionity" as the mobility+ app does it.

That would still make it confusing why there is a special option for Ionity in addition to the generic "Networks" option.

**Comment by johan12345** [comment]
closing in favor of #265
