### ISSUE TITLE
Close button doesn't work correctly

### ISSUE THREAD

**Issue by kepppfeff** [johan12345/EVMap#260]
When I open a charging station entry and scroll down to the bottom (where the link to GoingElectric is), I have the problem that the close button (on the top left) doesn't work correctly. If I press it, the detail view is moved down only partially so that I get an undefined state like here:

![Capture+_2022-11-22-23-43-02](https://user-images.githubusercontent.com/47675381/203437185-4f397d96-896c-4354-a465-403b238247e5.png)

In this case the price comparison button is not working and I also can not move the detail panel up and down any more, instead I can move the map laying behind it.

**Comment by johan12345** [comment]
I assume this occurs with the current version 1.4.2, right?

I couldn't reproduce it so far, but will try more thoroughly (with different Android versions, display sizes, etc.) when I have time.

It might be related to my recent changes here that were supposed to fix layout issues when the data in the detail panel is updated while it is currently moving (previously those changes were not rendered at all): https://github.com/johan12345/CustomBottomSheetBehavior/commit/3529a5a9f1f5ef271465ddbb501bee578e9ce2d2

**Comment by kepppfeff** [comment]
Correct, I use version 1.4.2-google and have Android 8.1.0.

**Comment by johan12345** [comment]
I was able to reproduce the bug now, even with older versions of the app. So it is not caused by the recent changes. Instead, it seems to be basically this issue: https://github.com/miguelhincapie/CustomBottomSheetBehavior/issues/46

Now I added a change that will reset the scroll position when the detail panel is closed: https://github.com/johan12345/CustomBottomSheetBehavior/commit/f4f641aab56cc392e2edc5c4b20e351399666fc3 This should fix it for the next update :)
