### ISSUE TITLE
Charge price comparison: switch between cars not consistent

### ISSUE THREAD

**Issue by Altonss** [johan12345/EVMap#312]
In the charge price comparaison menu, when switching to a car with only AC and then clicking back on a car that has DC, the selection remains AC while it was DC by default when opening the menu.
 Version 1.7.1 (F-Droid)

**Comment by johan12345** [comment]
Hmm, we could easily "solve" this by resetting to the first supported connector in the list every time you switch cars.

But that may also not be what you want (e.g., if you manually selected the AC port before switching cars, you probably want to keep it). To do it properly, we'd have to keep track of whether the selected connector has been changed and handle all kinds of different cases (e.g., what happens if you changed to a different connector and then switched back to the initial one?). Not sure if that's worth it.
