### ISSUE TITLE
Feature request : add link “report new station” to main menu

### ISSUE THREAD

**Issue by F3000** [johan12345/EVMap#53]
Could be useful to create a new menu item for following link :

https://www.goingelectric.de/stromtankstellen/new/

**Comment by johan12345** [comment]
Will be added in the next update ✔️

**Comment by F3000** [comment]
Thanks 😊 


Is the GE API capable of adding stations to ?

**Comment by johan12345** [comment]
> Is the GE API capable of adding stations to ?

No, unfortunately not.

> Is this in version 0.3.4 ?

Yes!

**Comment by TweetsOfNiklas** [comment]
I know there is no way to add a station via the API. But maybe that's too complicated for the casual user anyways.

The chargeprice app has solved this problem with a simple form (Where?, Who?, Addiditional Infos) which everyone can fill out. And someone on the backend adds the station. I mean I would't outsource this to developers on the backend. But maybe there could be something like "Discovered Charging Stations". 
The only problem I see here is the need of a necessary database. Maybe the app can send out a command which posts the infos in the GoingElectric EVMap Thread? Would that be even possible?

**Comment by johan12345** [comment]
In contrast to Chargeprice, who are a commercial company, I don't have the resources to process such user requests to add a charging station (and of course it is also difficult to verify them). And creating a separate database of "Discovered charging stations" would again increase the fragmentation of EV charging data sources (because it would be an additional data source only available through EVMap...).

> Maybe the app can send out a command which posts the infos in the GoingElectric EVMap Thread? Would that be even possible?

Might be possible, but I guess a bot posting on the forum would also be frowned upon by the GoingElectric website owner...
