### ISSUE TITLE
Use a Custom-API

### ISSUE THREAD

**Issue by dominikponniah** [johan12345/EVMap#89]
I would like to update the API-URI to another Service built by myself to display Gaz-Stations (Erdgas) instead of Electric-Stations. Where do I have to update these Data? Seems to be stored in various files.

**Comment by johan12345** [comment]
Hi - does your custom API have the exact same data format as the one from GoingElectric.de? Otherwise, this would probably not just mean updating the URL, but also changing many other things about how the app handles the data.

As I am currently looking into #81, I am currently working on adding an abstraction layer that makes it possible to add other API implementations with different data formats (and, eventually, switching between these data sources in the app). But still, the app contains many things that are specific to EV chargers (such as plug types, power in kW, realtime availability, etc.) that are not really applicable to gas pumps.

**Comment by dominikponniah** [comment]
Hey @johan12345 thanks for your reply!

I am planing just to create a dump-file and serve as JSON-File.  In this phase my main goal is just to add some custom data to your awesome app and then simply display these.

I know, especially Erdgas and Biogas do not have such informations like Plug-Data but in a second phase I would like to update or remove these properties.

My Goal is to display these Gas-Stations in the App and also later in the Android-Auto - App. 😊

**Comment by johan12345** [comment]
I'll close this for now as this is mainly a question about the codebase and not an issue that needs to be solved

**Comment by johan12345** [comment]
@dominikponniah Hey, I noticed that your new app [evMap](https://play.google.com/store/apps/details?id=ch.dominikponniah.evmap) uses basically the exact same name as this one... I know that it's not a registered trademark etc., but it is probably confusing for people trying to find any of the two apps - so have you thought about using another name maybe?

**Comment by dominikponniah** [comment]
@johan12345 Sure! Already done. I've called my App like this as I did not knew your app at this point.

I renamed my prototype to eleMap now 👍

**Comment by johan12345** [comment]
Ah, awesome, thank you! 👍🏻
