### ISSUE TITLE
Mapbox OutOfMemoryError

### ISSUE THREAD

**Issue by kelvan** [johan12345/EVMap#91]
App works well for me if I'm in Switzerland connected to Sunrise, but as soon as I cross the boarder to Austria evmap crashes short after starting/loading charging points.
I tried to work around by using a wifi hotspot from another phone, but still it crashes all the time when used outside Switzerland.
I'm using Android 9 on a Xiaomi Mi A1

**Comment by johan12345** [comment]
Interesting. Have you checked if your mobile provider is doing any strange stuff to your internet connection when roaming, such as forwarding you to a certain website? Can you use the charger map on the [Goingelectric website](https://www.goingelectric.de/stromtankstellen/) while roaming?

**Comment by kelvan** [comment]
I installed the play store version and was able to report the crash report with some luck (the popup asking to send the report disappears after <1s -.-)
It seems to crash with an out of memory exception.
Not sure why this always happen while I'm in Austria, but not in Switzerland.

**Comment by johan12345** [comment]
Hmm, I can't find your crash report in the Google Play console (nothing from a Xiaomi device with Android 9 in the last 7 days) 😞 There is an OutOfMemoryError that sometimes occurs with the Mapbox (OpenStreetMap) API, because it has problems deleting old icons from the cache. But that should only occur after using the app for a longer time.

**Comment by kelvan** [comment]
As I'm in Austria again today I was able to test again and sent another crash report, hopefully it arrives this time :)

also took some screenshots this time, something is weird with the android mem management on my phone anyway, often can't switch between two apps without one kicked out of mem -.-
I think need a 64GB phone to use more than one app, brave new world 👴

![image](https://user-images.githubusercontent.com/611853/126133835-b12e3fa5-b627-486f-8303-3f28309b0c68.png)
![image](https://user-images.githubusercontent.com/611853/126133853-0a93d14e-60c5-4a33-b715-e6fbdcba2ab3.png)
![image](https://user-images.githubusercontent.com/611853/126133873-41fb377e-c6ac-495d-b8f1-1861beaf6725.png)

**Comment by johan12345** [comment]
Thanks!

Hmm, yeah, this seems to be the Mapbox OutOfMemoryError that I talked about. The problem is that when we animate the map icons, we have to pass all of these Icons to Mapbox and Mapbox seems to keep them forever instead of deleting them if memory is needed.

Still strange that this happens for you only when you are in Austria, and also strange that it happens on a phone with 4 GB RAM, which should be plenty (same as my Pixel 3a, on which the app works fine)...

**Comment by johan12345** [comment]
One thing I could try is to use the deprecated [Icon API](https://docs.mapbox.com/android/maps/guides/annotations/#markers) of Mapbox instead of the new Annotation plugin for markers - it looks like that API is more similar to the one of Google Maps, so that icons don't need to be saved forever.

**Comment by johan12345** [comment]
I've just uploaded a new release 0.8.3 to the beta channel on Google Play (should be available there in a couple of hours) and to F-Droid (may take a few days for their server to build it), which uses this different approach to create the markers on Mapbox - this might be more stable. Please reopen if you still notice the same crash after the update :)
