### ISSUE TITLE
Searchinput not focused after tapping it

### ISSUE THREAD

**Issue by kelvan** [johan12345/EVMap#92]
**Steps to reproduce**

- Tap the search box
- Type something

**Expected behaviour**

Typed characters inserted into searchbox

**Current behaviour**

Keyboard opens, but it is necessary to tap the search input again to insert a search

**Comment by johan12345** [comment]
Is this happening the Google Play or the F-Droid version of the app? They use different SDKs for the search field (Google Places / Mapbox).

**Comment by kelvan** [comment]
Hi, sorry for the late response.
I used the fdroid version, I now installed it from play store and it works there.

**Comment by johan12345** [comment]
Yeah, the Mapbox version of PlacesAutocomplete does not request the focus. There is an open issue for this since 2 years: https://github.com/mapbox/mapbox-plugins-android/issues/1011 and a PR that included a fix for this as well as other changes (https://github.com/mapbox/mapbox-plugins-android/pull/968) has been closed as stale.

I have now opened a new PR that only fixes this issue: https://github.com/mapbox/mapbox-plugins-android/pull/1191

And for now, I'll include my fork of the library using JitPack so that the fix is already included.
